"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Upload } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "@/components/ui/use-toast";

type ImportResult = {
  success: boolean;
  message?: string;
  totalRows: number;
  imported: number;
  skippedDuplicates: number;
  skippedInvalid: number;
  errors: string[];
};

type BrowserOsImportButtonProps = {
  onImported: () => void | Promise<void>;
};

export function BrowserOsImportButton({
  onImported,
}: BrowserOsImportButtonProps) {
  const router = useRouter();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [importing, setImporting] = useState(false);
  const [result, setResult] = useState<ImportResult | null>(null);

  const resetDialog = (open: boolean) => {
    setDialogOpen(open);
    if (!open) {
      setSelectedFile(null);
      setResult(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    }
  };

  const importCsv = async () => {
    if (!selectedFile) {
      toast({
        variant: "destructive",
        title: "No CSV selected",
        description: "Choose the BrowserOS import-ready CSV first.",
      });
      return;
    }

    setImporting(true);
    setResult(null);

    try {
      const formData = new FormData();
      formData.append("file", selectedFile);

      const response = await fetch("/api/jobs/import/browseros", {
        method: "POST",
        body: formData,
      });
      const data = (await response.json()) as ImportResult;
      setResult(data);

      if (!response.ok || !data.success) {
        toast({
          variant: "destructive",
          title: "Import failed",
          description: data.message || "The CSV could not be imported.",
        });
        return;
      }

      toast({
        variant: "success",
        title: "Import complete",
        description: `${data.imported} imported, ${data.skippedDuplicates} duplicates skipped.`,
      });
      await onImported();
      router.refresh();
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Import failed",
        description:
          error instanceof Error ? error.message : "Unknown import error.",
      });
    } finally {
      setImporting(false);
    }
  };

  return (
    <>
      <Button
        size="sm"
        variant="outline"
        className="h-8 gap-1"
        onClick={() => setDialogOpen(true)}
      >
        <Upload className="h-3.5 w-3.5" />
        <span className="sr-only sm:not-sr-only sm:whitespace-nowrap">
          Import
        </span>
      </Button>
      <Dialog open={dialogOpen} onOpenChange={resetDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Import BrowserOS jobs</DialogTitle>
            <DialogDescription>
              Upload the import-ready CSV generated by the BrowserOS pipeline.
              This creates draft jobs and skips duplicates on repeat imports.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium" htmlFor="browseros-csv">
                CSV file
              </label>
              <Input
                id="browseros-csv"
                ref={fileInputRef}
                type="file"
                accept=".csv,text/csv"
                disabled={importing}
                onChange={(event) => {
                  setSelectedFile(event.target.files?.[0] ?? null);
                  setResult(null);
                }}
              />
              <p className="text-xs text-muted-foreground">
                Expected file: job_tracker_import_ready.csv.
              </p>
            </div>

            {result && (
              <div className="rounded-md border p-3 text-sm">
                <p>
                  Rows: {result.totalRows} · Imported: {result.imported} ·
                  Duplicates skipped: {result.skippedDuplicates} · Invalid
                  skipped: {result.skippedInvalid}
                </p>
                {result.errors.length > 0 && (
                  <ul className="mt-2 list-disc space-y-1 pl-5 text-muted-foreground">
                    {result.errors.map((error) => (
                      <li key={error}>{error}</li>
                    ))}
                  </ul>
                )}
              </div>
            )}
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => resetDialog(false)}
              disabled={importing}
            >
              Close
            </Button>
            <Button
              type="button"
              onClick={importCsv}
              disabled={importing || !selectedFile}
            >
              {importing && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Import CSV
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
